// [language, difficulty 1-3, question, options, correctIndex]
export const Q = [
['C',1,'int x = 5;\nprintf("%d", x++ + 1);\n\nWhat is printed?',['5','6','7','Compile error'],1],
['C',1,'Which is the safest way to read a line of text into a fixed buffer?',['gets()','fgets()','scanf("%s")','read_line()'],1],
['C',2,'int a[3] = {1,2,3};\nprintf("%d", *(a+2));\n\nWhat is printed?',['1','2','3','Garbage'],2],
['C',2,'char s[] = "hi";\nprintf("%zu", sizeof(s));\n\nWhat is printed?',['2','3','4','8'],1],
['C',3,'#define SQ(x) x*x\nprintf("%d", SQ(2+1));\n\nWhat is printed?',['9','5','6','Compile error'],1],
['C',3,'char *p = malloc(4);\nfree(p);\nfree(p);\n\nWhat is wrong here?',['Nothing','A memory leak','Double free (undefined behavior)','Compile error'],2],
['C++',1,'cout << 10 / 4;\n\nWhat is printed?',['2.5','2','3','2.0'],1],
['C++',1,'Which container stores unique keys in sorted order?',['vector','set','stack','queue'],1],
['C++',2,'int x = 5;\nint &r = x;\nr++;\ncout << x;\n\nWhat is printed?',['5','6','Compile error','Undefined'],1],
['C++',2,'Which keyword lets a derived class override a method through a base pointer?',['static','virtual','inline','extern'],1],
['C++',3,'vector<int> v = {1,2,3};\nfor (auto x : v) v.push_back(x);\n\nWhat happens?',['Doubles the vector safely','Prints nothing','Undefined behavior (iterator invalidation)','Compile error'],2],
['C++',3,'auto a = make_unique<int>(1);\nauto b = a;\n\nWhat happens?',['Both own the int','Compile error: copy is deleted','b is null','Runtime crash'],1],
['Java',1,'String a = "hi";\nString b = "hi";\nSystem.out.println(a == b);\n\nWhat is printed?',['true','false','Compile error','null'],0],
['Java',1,'What is the default value of an int field in a class?',['null','0','undefined','-1'],1],
['Java',2,'System.out.println(1 + 2 + "3" + 4 + 5);\n\nWhat is printed?',['3345','12345','1239','Compile error'],0],
['Java',2,'Which is NOT a valid Java access modifier?',['private','protected','internal','public'],2],
['Java',3,'Integer a=127, b=127, c=128, d=128;\nSystem.out.println((a==b) + " " + (c==d));\n\nWhat is printed?',['true true','true false','false false','false true'],1],
['Java',3,'Which interface must a class implement to be used in try-with-resources?',['Runnable','AutoCloseable','Serializable','Cloneable'],1],
['Python',1,'print(3 * "ab")\n\nWhat is printed?',['ababab','ab3','6','Error'],0],
['Python',1,'print(len({1, 2, 2, 3}))\n\nWhat is printed?',['4','3','2','Error'],1],
['Python',2,'x = [1, 2, 3]\ny = x\ny.append(4)\nprint(x)\n\nWhat is printed?',['[1, 2, 3]','[1, 2, 3, 4]','Error','[4]'],1],
['Python',2,'print(bool("False"))\n\nWhat is printed?',['False','True','Error','None'],1],
['Python',3,'def f(a, b=[]):\n    b.append(a)\n    return b\n\nf(1)\nprint(f(2))\n\nWhat is printed?',['[2]','[1, 2]','[1]','Error'],1],
['Python',3,'print([i*i for i in range(4) if i % 2])\n\nWhat is printed?',['[0, 4]','[1, 9]','[1, 4, 9]','[0, 1, 4, 9]'],1],
]
